name: Generate PDF from MD and upload artifact

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node JS
        uses: actions/setup-node@v2
        with:
          node-version: '15.12.0'
      - name: Install dependencies
        run: npm i -g md-to-pdf@4.0.0
      - name: Generate PDF
        run: md-to-pdf --config-file config/pdf.js Ilya_Siamionau_CV.html
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "Ilya_Siamionau_CV"
          path: Ilya_Siamionau_CV.pdf
