name: Generate PDF and upload artifact

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  generate_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Generate PDF
        run: |
          cd src
          npm install
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Ilya_Siamionau_CV"
          path: dist/Ilya_Siamionau_CV.pdf
